# action.yml
name: 'Constructor'
description: 'Construye un paquete bdist de setuptools con el plugin setuptools-rust'
inputs:
  comando:
    description: 'Comando de setuptools a ejecutar'
    required: true
    default: 'bdist'
outputs:
  ruta_paquete:
    description: 'Ruta del paquete producido'
  nombre_paquete:
    description: 'Nombre del paquete producido'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.comando }}
